import { StyleSheet } from "react-native";

export const onboardingStepStyles = StyleSheet.create({
  stepContent: {
    paddingTop: 12,
    paddingBottom: 12,
  },
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "800",
    color: "#1C1C1C",
  },
  subtitle: {
    marginTop: 8,
    marginBottom: 28,
    fontSize: 15,
    lineHeight: 22,
    color: "#6B6B6B",
  },
  input: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 16,
    color: "#1C1C1C",
    fontSize: 16,
  },
  textarea: {
    minHeight: 112,
    paddingTop: 16,
    textAlignVertical: "top",
  },
  shortTextarea: {
    minHeight: 84,
    paddingTop: 14,
    textAlignVertical: "top",
    marginTop: 16,
  },
  stack: {
    gap: 12,
  },
  sectionLabel: {
    marginTop: 20,
    marginBottom: 10,
    color: "#6B6B6B",
    fontSize: 13,
  },
  optionButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  optionButtonActive: {
    backgroundColor: "#E63946",
  },
  optionLabel: {
    flex: 1,
    color: "#1C1C1C",
    fontSize: 15,
    fontWeight: "600",
  },
  optionLabelActive: {
    color: "#FFFFFF",
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 20,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#F5F5F5",
  },
  chipActive: {
    backgroundColor: "#E63946",
  },
  chipText: {
    color: "#1C1C1C",
    fontSize: 14,
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  helperText: {
    marginTop: 24,
    marginBottom: 12,
    textAlign: "center",
    color: "#6B6B6B",
    fontSize: 13,
  },
  suggestionCard: {
    borderRadius: 14,
    backgroundColor: "#FFF5F4",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#FFE1DD",
  },
  suggestionText: {
    color: "#E63946",
    fontSize: 14,
    lineHeight: 20,
  },
  ageGrid: {
    justifyContent: "space-between",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ageChip: {
    width: "18.4%",
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
    justifyContent: "center",
  },
  ageChipActive: {
    backgroundColor: "#E63946",
  },
  ageChipText: {
    color: "#1C1C1C",
    fontWeight: "600",
  },
  ageChipTextActive: {
    color: "#FFFFFF",
  },
  dobHeroCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: "#FFF1EE",
    borderWidth: 1,
    borderColor: "#FFD9D2",
  },
  dobHeroEyebrow: {
    color: "#E63946",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  dobHeroTitle: {
    marginTop: 8,
    color: "#1C1C1C",
    fontSize: 22,
    fontWeight: "800",
  },
  dobHeroSubtitle: {
    marginTop: 6,
    color: "#6B6B6B",
    fontSize: 14,
    lineHeight: 21,
  },
  dobRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 22,
  },
  dobInputWrap: {
    flex: 1,
  },
  dobInputLabel: {
    marginBottom: 8,
    color: "#6B6B6B",
    fontSize: 13,
    fontWeight: "600",
  },
  dobInput: {
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 16,
    color: "#1C1C1C",
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  dobHint: {
    marginTop: 14,
    color: "#6B6B6B",
    fontSize: 13,
    lineHeight: 20,
  },
  dobAgeCard: {
    marginTop: 20,
    borderRadius: 18,
    padding: 16,
    backgroundColor: "#F5F5F5",
  },
  dobAgeLabel: {
    color: "#6B6B6B",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  dobAgeValue: {
    marginTop: 6,
    color: "#1C1C1C",
    fontSize: 24,
    fontWeight: "800",
  },
  dobAgeCaption: {
    marginTop: 4,
    color: "#6B6B6B",
    fontSize: 13,
    lineHeight: 19,
  },
  iconInputWrap: {
    position: "relative",
  },
  iconInput: {
    position: "absolute",
    top: 18,
    left: 16,
    zIndex: 1,
  },
  inputWithIcon: {
    paddingLeft: 46,
  },
  heroPhoto: {
    width: 192,
    height: 256,
    borderRadius: 20,
    alignSelf: "center",
  },
  heroPhotoWrap: {
    width: 192,
    height: 256,
    alignSelf: "center",
  },
  photoPlaceholder: {
    width: 192,
    height: 256,
    borderRadius: 20,
    alignSelf: "center",
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#ECECEC",
    backgroundColor: "#F5F5F5",
    alignItems: "center",
    justifyContent: "center",
  },
  photoRemoveButton: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
  },
  photoRemoveButtonText: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "700",
  },
  photoPlaceholderText: {
    color: "#6B6B6B",
    fontSize: 14,
  },
  samplePhotoRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  samplePhoto: {
    width: 64,
    height: 80,
    borderRadius: 10,
  },
  samplePhotoActive: {
    borderWidth: 2,
    borderColor: "#E63946",
  },
  counterText: {
    marginTop: 20,
    color: "#6B6B6B",
    fontSize: 14,
  },
  preferenceCard: {
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    padding: 16,
    marginBottom: 18,
  },
  preferenceLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  preferenceLabel: {
    color: "#1C1C1C",
    fontSize: 15,
    fontWeight: "700",
  },
  rangeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  rangeInput: {
    width: 72,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    textAlign: "center",
    color: "#1C1C1C",
    fontWeight: "600",
  },
  rangeInputWide: {
    width: 96,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    textAlign: "center",
    color: "#1C1C1C",
    fontWeight: "600",
  },
  rangeText: {
    color: "#6B6B6B",
    fontSize: 14,
  },
  preferenceHeading: {
    marginBottom: 12,
    color: "#1C1C1C",
    fontSize: 15,
    fontWeight: "700",
  },
});
